const numbers = [51, -3, 27, 21, -68, 42, -37];

const players = [
    { name: "Adam",         level:42,      role: "Warrior" },
    { name: "Beth",         level:1,       role: "Warrior" },
    { name: "Cecil",        level:7,       role: "Mage" },
    { name: "Dorothy",      level:74,      role: "Tank" },
    { name: "Faith",        level:69,      role: "Paladin" },
    { name: "Greg",         level:21,      role: "Archer" },
    { name: "Henry",        level:56,      role: "Mage" },
    { name: "Edmund",       level:99,      role: "Paladin" },
];

const posts = [
    {id: 1, title: "JS article",            tag: ["JavaScript", "CoffeeScript"]},
    {id: 2, title: "TS article",            tag: ["JavaScript", "TypeScript"]},
    {id: 3, title: "Web article",           tag: ["HTML", "CSS", "JavaScript"]},
    {id: 4, title: "Arrays article",        tag: ["JavaScript"]},
    {id: 5, title: "Architecture article",  tag: ["Java"]},
    {id: 6, title: "ML AI article",         tag: ["Python"]},
    {id: 7, title: "Blazingly article",     tag: ["Rust"]},
    {id: 8, title: "Maths article",         tag: ["Haskell", "Elixir"]},
]
const users = [
    {
      name: "Moore Hensley",
      email: "moorehensley@indexia.com",
      eyeColor: "blue",
      friends: ["Sharron Pace"],
      isActive: false,
      balance: 2811,
      skills: ["ipsum", "lorem"],
      gender: "male",
      age: 37,
    },
    {
      name: "Sharlene Bush",
      email: "sharlenebush@tubesys.com",
      eyeColor: "blue",
      friends: ["Briana Decker", "Sharron Pace"],
      isActive: true,
      balance: 3821,
      skills: ["tempor", "mollit", "commodo", "veniam", "laborum"],
      gender: "female",
      age: 34,
    },
    {
      name: "Ross Vazquez",
      email: "rossvazquez@xinware.com",
      eyeColor: "green",
      friends: ["Marilyn Mcintosh", "Padilla Garrison", "Naomi Buckner"],
      isActive: false,
      balance: 3793,
      skills: ["nulla", "anim", "proident", "ipsum", "elit"],
      gender: "male",
      age: 24,
    },
    {
      name: "Elma Head",
      email: "elmahead@omatom.com",
      eyeColor: "green",
      friends: ["Goldie Gentry", "Aisha Tran"],
      isActive: true,
      balance: 2278,
      skills: ["adipisicing", "irure", "velit"],
      gender: "female",
      age: 21,
    },
    {
      name: "Carey Barr",
      email: "careybarr@nurali.com",
      eyeColor: "blue",
      friends: ["Jordan Sampson", "Eddie Strong"],
      isActive: true,
      balance: 3951,
      skills: ["ex", "culpa", "nostrud"],
      gender: "male",
      age: 27,
    },
    {
      name: "Blackburn Dotson",
      email: "blackburndotson@furnigeer.com",
      eyeColor: "brown",
      friends: ["Jacklyn Lucas", "Linda Chapman"],
      isActive: false,
      balance: 1498,
      skills: ["non", "amet", "ipsum"],
      gender: "male",
      age: 38,
    },
    {
      name: "Sheree Anthony",
      email: "shereeanthony@kog.com",
      eyeColor: "brown",
      friends: ["Goldie Gentry", "Briana Decker"],
      isActive: true,
      balance: 2764,
      skills: ["lorem", "veniam", "culpa"],
      gender: "female",
      age: 39,
    },
  ];